name: publish

on:
    push:
        branches:
            - main

jobs:
    npm-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
            - run: git config --global user.email "twebber@tractorzoom.com"
            - run: git config --global user.name "Taylor Webber"
            - run: npm ci
            - name: Lerna Bootstrap
              run: ./node_modules/.bin/lerna bootstrap
            - name: Authenticate with NPM Registry
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
            - name: Lerna Publish
              run: ./node_modules/.bin/lerna publish --create-release github --yes
              env:
                  GH_TOKEN: ${{ github.token }}
